name: ${project.artifactId}
main: ${javaplugin.path}
version: ${project.version}
api-version: 1.17
depend: [Citizens, ModelEngine, MythicMobs, ItemsAdder]
commands:
  system:
    description: A set of admin-only utility subcommands.
