name: ${project.artifactId}
main: ${javaplugin.path}
version: ${project.version}
api-version: 1.17
depend: [Citizens, ModelEngine, MythicMobs, ItemsAdder, WraithLib]
commands:
  system:
    description: A set of admin-only utility subcommands.
  warp:
    description: Creates or teleports to existing warp points.
  warppad:
    description: Handles the management of warp pads.